### ISSUE TITLE
Seeding is duplicating lsitings

### ISSUE THREAD

**Issue by FaustCelaj** [mg-archie/real-finds#51]
when running the sed, the listings are being duplicated 

can add 

    console.log('Listings:', listings);
    console.log('agents:', agents)

after line 13 in homeroutes.js to console log the data coming in to see whats going on

![Image](https://github.com/mg-archie/real-finds/assets/149631014/a6cc5fbb-cbe4-46d2-a995-d78b0b3a9af5)
![Image](https://github.com/mg-archie/real-finds/assets/149631014/678d02d2-2271-4896-bc85-076f3c1014bf)

**Comment by mg-archie** [comment]
Corrected issue
